function fgC = fgCF(lambdal,in2,s1)
%FGCF
%    FGC = FGCF(LAMBDAL,IN2,S1)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    24-Sep-2017 20:14:44

fgC = [0.0;0.0;5.462386363636364;0.0;0.0;0.0];
