function intlim = intlimF(lambdal,in2)
%INTLIMF
%    INTLIM = INTLIMF(LAMBDAL,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    24-Sep-2017 20:18:48

q1 = in2(:,1);
intlim = q1;
