function ref = refF(lambdal,in2)
%REFF
%    REF = REFF(LAMBDAL,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    24-Sep-2017 20:14:43

q1 = in2(:,1);
q2 = in2(:,2);
q3 = in2(:,3);
t2 = q2.^2;
t3 = 1.0./q3.^2;
t4 = q3.^2;
t5 = t2+t4;
t6 = sqrt(t5);
t7 = q1.*t6.*(1.0./2.0);
t8 = sin(t7);
t9 = t2.*t3;
t10 = t9+1.0;
t11 = 1.0./t10;
ref = [q1.*t8.*t11-q1.*t2.*t3.*t8.*t11,(q1.*q2.*t8.*t11.*2.0)./q3,q1.*cos(t7)+1.0./1.0e2];
