function r_jtip = rjtipF(lambdal,in2)
%RJTIPF
%    R_JTIP = RJTIPF(LAMBDAL,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    24-Sep-2017 20:14:43

q1 = in2(:,1);
q2 = in2(:,2);
q3 = in2(:,3);
t2 = q2.^2;
t3 = 1.0./q3.^2;
t4 = q3.^2;
t5 = t2+t4;
t6 = sqrt(t5);
t7 = q1.*t6.*(1.0./2.0);
t8 = sin(t7);
t9 = t2.*t3;
t10 = t9+1.0;
t11 = 1.0./t10;
t12 = q1.*t8.*t11;
t19 = q1.*t2.*t3.*t8.*t11;
t13 = t12-t19;
t14 = 1.0./q3;
t15 = q1.*q2.*t8.*t11.*t14.*2.0;
t16 = cos(t7);
t17 = q1.*t16;
t18 = t17+1.0./1.0e2;
t20 = q1.*t6;
t21 = sin(t20);
t22 = 1.0./sqrt(t10);
r_jtip = reshape([0.0,t13,0.0,t15,1.0./1.0e2,t18,t13,t12-t19+t21.*t22.*(2.7e1./5.0e2),t15,t15+q2.*t14.*t21.*t22.*(2.7e1./5.0e2),t18,t17+cos(t20).*(2.7e1./5.0e2)+1.0./1.0e2],[2,6]);
