function MC = MCF(lambdal,in2,s1)
%MCF
%    MC = MCF(LAMBDAL,IN2,S1)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    24-Sep-2017 20:14:58

MC = reshape([4.9e1./8.8e1,0.0,0.0,0.0,0.0,0.0,0.0,4.9e1./8.8e1,0.0,0.0,0.0,0.0,0.0,0.0,4.9e1./8.8e1,0.0,0.0,0.0,0.0,0.0,0.0,7.987119890209199e-5,0.0,0.0,0.0,0.0,0.0,0.0,7.987119890209199e-5,0.0,0.0,0.0,0.0,0.0,0.0,-1.359518165646782e-7],[6,6]);
