function fj = fjF(lambda,in2)
%FJF
%    FJ = FJF(LAMBDA,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    03-Nov-2017 13:34:35

fj = [0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0];
