function ref = refF(lambda,in2)
%REFF
%    REF = REFF(LAMBDA,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    03-Nov-2017 13:34:34

q1 = in2(:,1);
q2 = in2(:,2);
q3 = in2(:,3);
ref = [q1,q2,q3];
