function r_jtip = rjtipF(lambda,in2)
%RJTIPF
%    R_JTIP = RJTIPF(LAMBDA,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    03-Nov-2017 13:34:34

q1 = in2(:,1);
q2 = in2(:,2);
q3 = in2(:,3);
q4 = in2(:,4);
q5 = in2(:,5);
q6 = in2(:,6);
q7 = in2(:,7);
q8 = in2(:,8);
q9 = in2(:,9);
q10 = in2(:,10);
q11 = in2(:,11);
q12 = in2(:,12);
q13 = in2(:,13);
q14 = in2(:,14);
q15 = in2(:,15);
q16 = in2(:,16);
q17 = in2(:,17);
q18 = in2(:,18);
q19 = in2(:,19);
q20 = in2(:,20);
q21 = in2(:,21);
r_jtip = reshape([q1,q4,q7,q10,q13,q16,q19,q2,q5,q8,q11,q14,q17,q20,q3,q6,q9,q12,q15,q18,q21,q1,q4,q7,q10,q13,q16,q19,q2,q5,q8,q11,q14,q17,q20,q3+1.0./1.0e2,q6+1.0./1.0e2,q9+1.0./1.0e2,q12+1.0./1.0e2,q15+1.0./1.0e2,q18+1.0./1.0e2,q21+1.0./1.0e2],[7,6]);
